services:
  _defaults:
    public: true

  monei.module:
    class: 'Monei'
    factory: ['Module', 'getInstanceByName']
    public: true
    arguments:
      - 'monei'

  monei.legacy.context:
    class: 'Monei'
    factory: ['@monei.module', 'getLegacyContext']

  monei.dbal.connection:
    class: 'Monei'
    factory: ['@monei.module', 'getDbalConnection']

  monei.legacy.configuration:
    class: 'Monei'
    public: true
    factory: ['@monei.module', 'getLegacyConfiguration']

  monei.prestashop.core.cache_clearer_chain:
    class: 'Monei'
    factory: ['@monei.module', 'getCacheClearerChain']

# REPOSITORIES
  monei.repository.monei_payment:
    class: 'PsMonei\Repository\MoneiPaymentRepository'
    factory: ['@monei.module', 'getRepository']
    arguments:
      - 'PsMonei\Entity\MoPayment'

  monei.repository.monei_token:
    class: 'PsMonei\Repository\MoneiTokenRepository'
    factory: ['@monei.module', 'getRepository']
    arguments:
      - 'PsMonei\Entity\MoToken'

  monei.repository.monei_history:
    class: 'PsMonei\Repository\MoneiHistoryRepository'
    factory: ['@monei.module', 'getRepository']
    arguments:
      - 'PsMonei\Entity\MoHistory'

  monei.repository.monei_refund:
    class: 'PsMonei\Repository\MoneiRefundRepository'
    factory: ['@monei.module', 'getRepository']
    arguments:
      - 'PsMonei\Entity\MoRefund'