<?php
namespace PsMonei\Exception;

use Exception;

class MoneiException extends Exception
{
    const CART_NOT_FOUND = 100;
    const CART_AMOUNT_EMPTY = 101;
    const CURRENCY_NOT_FOUND = 102;
    const CUSTOMER_NOT_FOUND = 103;
    const ADDRESS_NOT_FOUND = 104;
    const MONEI_API_KEY_IS_EMPTY = 105;
    const MONEI_CLIENT_NOT_INITIALIZED = 106;
    const PAYMENT_REQUEST_NOT_VALID = 107;
    const ORDER_NOT_FOUND = 108;
    const MONEI_ACCOUNT_ID_IS_EMPTY = 109;
    const MONEI_ACCOUNT_INFORMATION_NOT_FOUND = 110;
    const INVALID_JSON_RESPONSE = 111;
    const INVALID_CRYPTO_HASH = 112;
    const REFUND_AMOUNT_MUST_BE_GREATER_THAN_ZERO = 113;
    const REFUND_AMOUNT_EXCEEDS_AVAILABLE_REFUNDABLE_BALANCE = 114;
    const REFUND_CREATION_FAILED = 115;
    const CART_SUMMARY_DETAILS_EMPTY = 116;
    const INVALID_CURRENCY_ID_PROVIDED = 117;
    const COUNTRY_NOT_FOUND = 118;
    const SAVE_ENTITY_ERROR = 119;
    const REMOVE_ENTITY_ERROR = 120;
}
