name: Create Archive
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: '7z'
        filename: 'monei.zip'
        exclusions: '*.git* /build/*'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        artifacts: 'monei.zip'
        artifactContentType: 'application/zip'
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
