name: Create Archive
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: php-actions/composer@v6

    - name: Archive Release
      run: |
        mkdir ../monei
        cp -r . ../monei/
        cd ..
        zip -r monei.zip monei -x '*.git*' -x '/build/*'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        artifacts: '../monei.zip'
        artifactContentType: 'application/zip'
        token: ${{ secrets.GITHUB_TOKEN }}
