name: Create Archive
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Prepare Archive Directory
      run: |
        mkdir ../monei
        cp -r . ../monei/

    - name: Archive Release
      run: |
        cd ..
        zip -r monei.zip monei -x '*.git*' -x 'build/*'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        artifacts: '../monei.zip'
        artifactContentType: 'application/zip'
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
